package app.mashlab.autopreview.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes the Robolectric test that renders `AutoPreviewRegistry` (generated by the KSP processor in
 * the same package) and records `manifest.json` for the report.
 */
@CacheableTask
abstract class GenerateRenderTestTask : DefaultTask() {
    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val testJavaVersion: Property<Int>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val pkg = packageName.get()
        // Robolectric needs Java 21 for SDK 35+; older JDKs fall back to the newest SDK they can run.
        val config = if (testJavaVersion.get() < 21) {
            logger.warn(
                "Compose Auto Preview: unit tests run on Java ${testJavaVersion.get()}, " +
                    "rendering with SDK $FALLBACK_SDK. " +
                    "Use JDK 21 (e.g. Android Studio's bundled JBR) to render with your target SDK.",
            )
            "@Config(sdk = [$FALLBACK_SDK])"
        } else {
            ""
        }
        val dir = outputDir
            .get()
            .asFile
            .apply { deleteRecursively() }
        dir
            .resolve(pkg.replace('.', '/'))
            .apply { mkdirs() }
            .resolve("AutoPreviewRenderTest.kt")
            .writeText(TEMPLATE.replace("__PACKAGE__", pkg).replace("__CONFIG__", config))
    }
}

private const val FALLBACK_SDK = 34

private val TEMPLATE = """
package __PACKAGE__

import android.content.ContentProvider
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Path
import android.graphics.Rect
import android.graphics.RectF
import android.graphics.Typeface
import android.os.Looper
import android.view.Gravity
import android.view.View
import android.view.WindowManager
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.runtime.Recomposer
import androidx.compose.ui.platform.AndroidUiDispatcher
import androidx.compose.ui.platform.InfiniteAnimationPolicy
import androidx.core.graphics.Insets
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsCompat
import java.io.File
import java.time.Duration
import org.junit.Assume.assumeTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.Robolectric
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.Shadows.shadowOf
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.awaitCancellation
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch

// Generated by the Compose Auto Preview Gradle plugin. Run via `./gradlew autoPreview`.
@RunWith(RobolectricTestRunner::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
__CONFIG__
class AutoPreviewRenderTest {

    @Test
    fun render() {
        // Skipped in regular unit test runs; only `autoPreviewRender` sets the output dir and module.
        val outputPath: String? = System.getProperty("autopreview.outputDir")
        assumeTrue(outputPath != null)
        val outputDir = File(outputPath!!)
        outputDir.deleteRecursively()
        outputDir.mkdirs()
        startComposeResources()
        val screens = AutoPreviewRegistry.screens.map { screen ->
            val cells = screen.devices.flatMap { device ->
                screen.themes.flatMap { theme ->
                    screen.samples.mapIndexed { index, sample ->
                        val image = "${'$'}{screen.id}/${'$'}{device.name}/${'$'}{theme}/${'$'}sample.png"
                        val error = runCatching { capture(screen, device, theme, index, File(outputDir, image)) }
                            .exceptionOrNull()
                        "{" + listOf(
                            "device" to device.name,
                            "theme" to theme,
                            "sample" to sample,
                            "image" to image,
                            "error" to error?.let { it.toString() },
                        ).joinToString(",") { (key, value) -> json(key) + ":" + json(value) } + "}"
                    }
                }
            }
            "{" + listOf(
                json("id") + ":" + json(screen.id),
                json("navigatesTo") + ":" + screen.navigatesTo.joinToString(",", "[", "]") { json(it) },
                json("entryPoint") + ":" + screen.entryPoint,
                json("group") + ":" + json(screen.group),
                json("devices") + ":" + screen.devices.joinToString(",", "[", "]") {
                    "{" + json("name") + ":" + json(it.name) + "," + json("widthDp") + ":" + it.widthDp + "," +
                        json("heightDp") + ":" + it.heightDp + "," + json("round") + ":" + it.isRound + "}"
                },
                json("themes") + ":" + screen.themes.joinToString(",", "[", "]") { json(it) },
                json("samples") + ":" + screen.samples.joinToString(",", "[", "]") { json(it) },
                json("cells") + ":" + cells.joinToString(",", "[", "]"),
            ).joinToString(",") + "}"
        }
        val module = json(System.getProperty("autopreview.module"))
        File(outputDir, "manifest.json")
            .writeText(screens.joinToString(",", "{\"density\":2,\"module\":${'$'}module,\"screens\":[", "]}"))
    }

    private fun capture(screen: AutoPreviewScreen, device: AutoPreviewDevice, theme: String, index: Int, file: File) {
        val night = if (theme == "Dark") "night" else "notnight"
        RuntimeEnvironment.setQualifiers("${'$'}{screen.locale}-${'$'}{device.qualifiers}-${'$'}night-xhdpi")
        val existingWindows = rootViewNames()
        val controller = Robolectric.buildActivity(ComponentActivity::class.java).setup()
        val scope = CoroutineScope(AndroidUiDispatcher.Main + FreezeInfiniteAnimations)
        val recomposer = Recomposer(scope.coroutineContext)
        scope.launch { recomposer.runRecomposeAndApplyChanges() }
        try {
            val activity = controller.get()
            // Library test manifests have no app theme, so the framework default would draw a title bar.
            activity.actionBar?.hide()
            activity.window.decorView.setBackgroundColor(screen.backgroundColor.toInt())
            val systemBars = device.name in SYSTEM_BAR_DEVICES
            // Edge to edge, as apps targeting SDK 35+ always are, so content lays out around the system bars.
            if (systemBars) WindowCompat.setDecorFitsSystemWindows(activity.window, false)
            activity.setContent(parent = recomposer) { screen.content(index) }
            // Robolectric has no system bars, so their insets are handed to each window, again once dialogs and
            // sheets have opened theirs.
            repeat(2) {
                shadowOf(Looper.getMainLooper()).idleFor(Duration.ofMillis(250))
                if (systemBars) (rootViewNames() - existingWindows).forEach { rootView(it).dispatchApplyWindowInsets(systemBarInsets()) }
            }
            shadowOf(Looper.getMainLooper()).idleFor(Duration.ofMillis(250))
            val windows = (rootViewNames() - existingWindows).map(::rootView)
            file.parentFile?.mkdirs()
            val bitmap = drawScreen(windows)
            if (systemBars) drawSystemBars(Canvas(bitmap), dark = theme == "Dark")
            file.outputStream().use { bitmap.compress(Bitmap.CompressFormat.PNG, 100, it) }
        } finally {
            controller.pause().stop().destroy()
            recomposer.cancel()
            scope.cancel()
        }
    }

    // Compose Multiplatform resources get their Context from a ContentProvider, which library host tests don't start.
    @Suppress("UNCHECKED_CAST")
    private fun startComposeResources() {
        val provider = runCatching { Class.forName("org.jetbrains.compose.resources.AndroidContextProvider") }
            .getOrNull() ?: return
        Robolectric.setupContentProvider(provider as Class<ContentProvider>)
    }

    // Draws every window (activity + dialogs/popups) in z-order, so dialogs render like on device.
    private fun drawScreen(windows: List<View>): Bitmap {
        val resources = RuntimeEnvironment.getApplication().resources
        val bitmap = Bitmap.createBitmap(
            resources.displayMetrics.widthPixels,
            resources.displayMetrics.heightPixels,
            Bitmap.Config.ARGB_8888,
        )
        val canvas = Canvas(bitmap)
        if (resources.configuration.isScreenRound) {
            val radius = bitmap.width / 2f
            canvas.clipPath(Path().apply { addCircle(radius, bitmap.height / 2f, radius, Path.Direction.CW) })
        }
        val display = Rect(0, 0, bitmap.width, bitmap.height)
        val frame = Rect()
        windows.forEach { view ->
            val params = view.layoutParams as WindowManager.LayoutParams
            if (params.flags and WindowManager.LayoutParams.FLAG_DIM_BEHIND != 0) {
                canvas.drawColor(Color.argb((params.dimAmount * 255).toInt(), 0, 0, 0))
            }
            // Robolectric lays every window out at 0,0; position it the way WindowManager would.
            Gravity.apply(params.gravity, view.width, view.height, display, params.x, params.y, frame)
            canvas.save()
            canvas.translate(frame.left.toFloat(), frame.top.toFloat())
            view.draw(canvas)
            canvas.restore()
        }
        return bitmap
    }

    private fun dp(value: Float) = value * RuntimeEnvironment.getApplication().resources.displayMetrics.density

    private fun systemBarInsets() = WindowInsetsCompat.Builder()
        .setInsets(WindowInsetsCompat.Type.statusBars(), Insets.of(0, dp(STATUS_BAR_DP).toInt(), 0, 0))
        .setInsets(WindowInsetsCompat.Type.navigationBars(), Insets.of(0, 0, 0, dp(NAVIGATION_BAR_DP).toInt()))
        .build()
        .toWindowInsets()!!

    // A Pixel-style status bar (clock left; signal, wifi and battery right) and gesture handle, over every window as
    // on device. Icons are dark on light themes and light on dark ones.
    private fun drawSystemBars(canvas: Canvas, dark: Boolean) {
        val width = canvas.width.toFloat()
        val height = canvas.height.toFloat()
        val paint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = if (dark) Color.WHITE else Color.rgb(31, 31, 31) }
        val middle = dp(STATUS_BAR_DP) / 2
        paint.textSize = dp(14f)
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("9:30", dp(24f), middle - (paint.descent() + paint.ascent()) / 2, paint)

        val battery = RectF(width - dp(24f) - dp(9f), middle - dp(7f), width - dp(24f), middle + dp(7f))
        canvas.drawRoundRect(battery, dp(2f), dp(2f), paint)
        canvas.drawRect(battery.left + dp(2.5f), battery.top - dp(1.5f), battery.right - dp(2.5f), battery.top, paint)
        val wifiRight = battery.left - dp(8f)
        val wifi = RectF(wifiRight - dp(16f), middle - dp(6f), wifiRight, middle + dp(10f))
        canvas.drawArc(wifi, 225f, 90f, true, paint)
        val signalRight = wifi.left - dp(6f)
        canvas.drawPath(
            Path().apply {
                moveTo(signalRight, middle - dp(6f))
                lineTo(signalRight, middle + dp(6f))
                lineTo(signalRight - dp(12f), middle + dp(6f))
                close()
            },
            paint,
        )

        val handle = RectF(width / 2 - dp(36f), 0f, width / 2 + dp(36f), dp(4f))
        handle.offset(0f, height - dp(NAVIGATION_BAR_DP) / 2 - dp(2f))
        paint.alpha = 0xB0
        canvas.drawRoundRect(handle, dp(2f), dp(2f), paint)
    }

    // Infinite animations (progress indicators, shimmers) would otherwise keep the frame loop busy forever.
    private object FreezeInfiniteAnimations : InfiniteAnimationPolicy {
        override suspend fun <R> onInfiniteOperation(block: suspend () -> R): R = awaitCancellation()
    }

    private val windowManagerGlobal = Class.forName("android.view.WindowManagerGlobal")
    private val windowManager = windowManagerGlobal.getMethod("getInstance").invoke(null)

    @Suppress("UNCHECKED_CAST")
    private fun rootViewNames(): List<String> =
        (windowManagerGlobal.getMethod("getViewRootNames").invoke(windowManager) as Array<String>).toList()

    private fun rootView(name: String): View =
        windowManagerGlobal.getMethod("getRootView", String::class.java).invoke(windowManager, name) as View

    private companion object {
        val SYSTEM_BAR_DEVICES = setOf("Phone", "Tablet", "Foldable")
        const val STATUS_BAR_DP = 24f
        const val NAVIGATION_BAR_DP = 24f
    }

    private fun json(value: String?): String = value?.let {
        "\"" + it.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "") + "\""
    } ?: "null"
}
""".trimStart()
