package app.mashlab.autopreview.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Writes the Robolectric test that renders `AutoPreviewRegistry` (generated by the KSP processor in
 * the same package) and records `manifest.json` for the report.
 */
@CacheableTask
abstract class GenerateRenderTestTask : DefaultTask() {
    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val testJavaVersion: Property<Int>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val pkg = packageName.get()
        // Robolectric needs Java 21 for SDK 35+; older JDKs fall back to the newest SDK they can run.
        val config = if (testJavaVersion.get() < 21) {
            logger.warn(
                "Compose Auto Preview: unit tests run on Java ${testJavaVersion.get()}, " +
                    "rendering with SDK $FALLBACK_SDK. " +
                    "Use JDK 21 (e.g. Android Studio's bundled JBR) to render with your target SDK.",
            )
            "@Config(sdk = [$FALLBACK_SDK])"
        } else {
            ""
        }
        val dir = outputDir
            .get()
            .asFile
            .apply { deleteRecursively() }
        dir
            .resolve(pkg.replace('.', '/'))
            .apply { mkdirs() }
            .resolve("AutoPreviewRenderTest.kt")
            .writeText(TEMPLATE.replace("__PACKAGE__", pkg).replace("__CONFIG__", config))
    }
}

private const val FALLBACK_SDK = 34

private val TEMPLATE = """
package __PACKAGE__

import android.content.ContentProvider
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Path
import android.graphics.Rect
import android.os.Looper
import android.view.Gravity
import android.view.View
import android.view.WindowManager
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.runtime.Recomposer
import androidx.compose.ui.platform.AndroidUiDispatcher
import androidx.compose.ui.platform.InfiniteAnimationPolicy
import java.io.File
import java.time.Duration
import org.junit.Assume.assumeTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.Robolectric
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.Shadows.shadowOf
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.awaitCancellation
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch

// Generated by the Compose Auto Preview Gradle plugin. Run via `./gradlew autoPreview`.
@RunWith(RobolectricTestRunner::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
__CONFIG__
class AutoPreviewRenderTest {

    @Test
    fun render() {
        // Skipped in regular unit test runs; only `autoPreviewRender` sets the output dir and module.
        val outputPath: String? = System.getProperty("autopreview.outputDir")
        assumeTrue(outputPath != null)
        val outputDir = File(outputPath!!)
        outputDir.deleteRecursively()
        outputDir.mkdirs()
        startComposeResources()
        val screens = AutoPreviewRegistry.screens.map { screen ->
            val cells = screen.devices.flatMap { device ->
                screen.themes.flatMap { theme ->
                    screen.samples.mapIndexed { index, sample ->
                        val image = "${'$'}{screen.id}/${'$'}{device.name}/${'$'}{theme}/${'$'}sample.png"
                        val error = runCatching { capture(screen, device, theme, index, File(outputDir, image)) }
                            .exceptionOrNull()
                        "{" + listOf(
                            "device" to device.name,
                            "theme" to theme,
                            "sample" to sample,
                            "image" to image,
                            "error" to error?.let { it.toString() },
                        ).joinToString(",") { (key, value) -> json(key) + ":" + json(value) } + "}"
                    }
                }
            }
            "{" + listOf(
                json("id") + ":" + json(screen.id),
                json("navigatesTo") + ":" + screen.navigatesTo.joinToString(",", "[", "]") { json(it) },
                json("entryPoint") + ":" + screen.entryPoint,
                json("devices") + ":" + screen.devices.joinToString(",", "[", "]") {
                    "{" + json("name") + ":" + json(it.name) + "," + json("widthDp") + ":" + it.widthDp + "," +
                        json("heightDp") + ":" + it.heightDp + "," + json("round") + ":" + it.isRound + "}"
                },
                json("themes") + ":" + screen.themes.joinToString(",", "[", "]") { json(it) },
                json("samples") + ":" + screen.samples.joinToString(",", "[", "]") { json(it) },
                json("cells") + ":" + cells.joinToString(",", "[", "]"),
            ).joinToString(",") + "}"
        }
        val module = json(System.getProperty("autopreview.module"))
        File(outputDir, "manifest.json")
            .writeText(screens.joinToString(",", "{\"density\":2,\"module\":${'$'}module,\"screens\":[", "]}"))
    }

    private fun capture(screen: AutoPreviewScreen, device: AutoPreviewDevice, theme: String, index: Int, file: File) {
        val night = if (theme == "Dark") "night" else "notnight"
        RuntimeEnvironment.setQualifiers("${'$'}{screen.locale}-${'$'}{device.qualifiers}-${'$'}night-xhdpi")
        val existingWindows = rootViewNames()
        val controller = Robolectric.buildActivity(ComponentActivity::class.java).setup()
        val scope = CoroutineScope(AndroidUiDispatcher.Main + FreezeInfiniteAnimations)
        val recomposer = Recomposer(scope.coroutineContext)
        scope.launch { recomposer.runRecomposeAndApplyChanges() }
        try {
            val activity = controller.get()
            // Library test manifests have no app theme, so the framework default would draw a title bar.
            activity.actionBar?.hide()
            activity.window.decorView.setBackgroundColor(screen.backgroundColor.toInt())
            activity.setContent(parent = recomposer) { screen.content(index) }
            shadowOf(Looper.getMainLooper()).idleFor(Duration.ofMillis(500))
            val windows = (rootViewNames() - existingWindows).map(::rootView)
            file.parentFile?.mkdirs()
            file.outputStream().use { drawScreen(windows).compress(Bitmap.CompressFormat.PNG, 100, it) }
        } finally {
            controller.pause().stop().destroy()
            recomposer.cancel()
            scope.cancel()
        }
    }

    // Compose Multiplatform resources get their Context from a ContentProvider, which library host tests don't start.
    @Suppress("UNCHECKED_CAST")
    private fun startComposeResources() {
        val provider = runCatching { Class.forName("org.jetbrains.compose.resources.AndroidContextProvider") }
            .getOrNull() ?: return
        Robolectric.setupContentProvider(provider as Class<ContentProvider>)
    }

    // Draws every window (activity + dialogs/popups) in z-order, so dialogs render like on device.
    private fun drawScreen(windows: List<View>): Bitmap {
        val resources = RuntimeEnvironment.getApplication().resources
        val bitmap = Bitmap.createBitmap(
            resources.displayMetrics.widthPixels,
            resources.displayMetrics.heightPixels,
            Bitmap.Config.ARGB_8888,
        )
        val canvas = Canvas(bitmap)
        if (resources.configuration.isScreenRound) {
            val radius = bitmap.width / 2f
            canvas.clipPath(Path().apply { addCircle(radius, bitmap.height / 2f, radius, Path.Direction.CW) })
        }
        val display = Rect(0, 0, bitmap.width, bitmap.height)
        val frame = Rect()
        windows.forEach { view ->
            val params = view.layoutParams as WindowManager.LayoutParams
            if (params.flags and WindowManager.LayoutParams.FLAG_DIM_BEHIND != 0) {
                canvas.drawColor(Color.argb((params.dimAmount * 255).toInt(), 0, 0, 0))
            }
            // Robolectric lays every window out at 0,0; position it the way WindowManager would.
            Gravity.apply(params.gravity, view.width, view.height, display, params.x, params.y, frame)
            canvas.save()
            canvas.translate(frame.left.toFloat(), frame.top.toFloat())
            view.draw(canvas)
            canvas.restore()
        }
        return bitmap
    }

    // Infinite animations (progress indicators, shimmers) would otherwise keep the frame loop busy forever.
    private object FreezeInfiniteAnimations : InfiniteAnimationPolicy {
        override suspend fun <R> onInfiniteOperation(block: suspend () -> R): R = awaitCancellation()
    }

    private val windowManagerGlobal = Class.forName("android.view.WindowManagerGlobal")
    private val windowManager = windowManagerGlobal.getMethod("getInstance").invoke(null)

    @Suppress("UNCHECKED_CAST")
    private fun rootViewNames(): List<String> =
        (windowManagerGlobal.getMethod("getViewRootNames").invoke(windowManager) as Array<String>).toList()

    private fun rootView(name: String): View =
        windowManagerGlobal.getMethod("getRootView", String::class.java).invoke(windowManager, name) as View

    private fun json(value: String?): String = value?.let {
        "\"" + it.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "") + "\""
    } ?: "null"
}
""".trimStart()
